# Generated by Django 5.1.4 on 2025-01-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_expenses_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
